server:
  port: 8082
  servlet:
    contextPath: /exkc

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8088/realms/exkc}
          jwk-set-uri: ${JWT_JWK_ISSUER_URI:http://localhost:8088/realms/exkc/protocol/openid-connect/certs}