server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8088/realms/exkc}
          jwk-set-uri: ${JWT_JWK_ISSUER_URI:http://localhost:8088/realms/exkc/protocol/openid-connect/certs}

cors:
  allowed:
    origins: http://localhost:9090

api:
  keycloak:
    clientSecret: xxx
    clientId: admin-spring-boot
    serverUrl: http://localhost:8088/auth
    realm: exkc
    grantType: client_credentials
    tmpPassword: "xxxxxxxxxxxx"
    defaultRole: default-roles-test
